language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libyaml-dev libssl-dev

install:
  - "python setup.py install"

